name: Build and Test ROS2 Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS2 environment
        run: |
          sudo apt update
          sudo apt install -y software-properties-common curl
          sudo add-apt-repository universe
          curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu focal main" > /etc/apt/sources.list.d/ros2-latest.list'
          sudo apt update
          sudo apt install -y ros-foxy-desktop python3-colcon-common-extensions
          echo "source /opt/ros/foxy/setup.bash" >> $GITHUB_ENV

      - name: Setup workspace
        run: |
          mkdir -p ~/ros2_ws/src
          cp -r . ~/ros2_ws/src/
          cd ~/ros2_ws
          source /opt/ros/foxy/setup.bash

      - name: Build package
        run: |
          cd ~/ros2_ws
          colcon build

      - name: Run tests
        run: |
          cd ~/ros2_ws
          colcon test

